"""yourmessage

Revision ID: cd53f9560c9b
Revises: d9d2af7cc4f4
Create Date: 2024-04-08 09:13:51.970999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd53f9560c9b'
down_revision = 'd9d2af7cc4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
